version: '3.4'

networks:
  backend:
    driver: bridge

services:
  workspace:
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    volumes:
      - ../:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7.30
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example
    volumes:
     - .data/mysql:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306