version: '3.4'

networks:
  backend:
    driver: bridge

services:
  workspace:
    tty: true
    build:
      dockerfile: Dockerfile
      context: ./workspace
    restart: always
    volumes:
      - ../:/var/www/html
    networks:
      - backend

  mysql:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mysql
    volumes:
      - ./mysql/.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monolog_mysql_sample
    networks:
      - backend
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: always
    ports:
      - "80:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - backend
